### ISSUE TITLE
Chat Log

### ISSUE THREAD

**Issue by chiefblck** [SenkaWolf/FiveM_Standalone-RP-Chat-Command-Basic-Pack#2]
Hey SenkaWolf , 
is there an option to log all the stuff which is writen by players ? 
So if someone writes something i can see later on.

**Comment by SenkaWolf** [comment]
No there isn't any builtin logging in this script. I know there is a script which logs the chat to a Discord channel but that's about it.

**Comment by chiefblck** [comment]
Okay. What is the name of this script which logs to discord ?

**Comment by SenkaWolf** [comment]
Hey @chiefblck sorry for the delayed response to this I thought I had replied! The method I have used before in the past can be seen in this link https://forum.cfx.re/t/release-server-log-to-discord/181213
